baseurl = "https://zech.co"
title = "Adrian Zech"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Adrian Zech"
  info = "Working on some stuff"
  description = "Adrian Zech's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "adrian@zech.co"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Enter Text..."
  hideFooter = true
  hideCredits = true
  hideCopyright = true
  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/adrianzech/"

# Menu links
[[menu.main]]
  name = "Wiki"
  weight = 1
  url = "https://wiki.zech.co"

